version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'denshanif'
      MYSQL_PASSWORD: '090202'
      MYSQL_ROOT_PASSWORD: '090202'
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: